### ISSUE TITLE
SmartRevise blocking driver-controlled browsers from logging in

### ISSUE THREAD

**Issue by Pixel1011** [Dinoosawruss/Automatic-Smart-Revise#3] opened 2020-12-11 00:17 UTC
(terrible title I know)

for me, it just throws me to the login screen which auto redirects you to logout

Admin Edits:
Updated title

**Issue Summary:**
SR automatically logging people out when using Automatic SR

**Issue identified:**
SR is blocking driver-controller browsers

**Potential Fixes:**
*if they have been attempted they will have a tick next to them*
- [x] **FAILED** Changing the `cdc_` string in chrome driver (see [this](https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver) for more info)
- [x] **FAILED** Change user agent

**ISSUE CLOSED**
"Found a [section of SmartRevise](https://smartrevise.online/robots.txt) that requests that people do not use automation on their site. I feel it is best to respect this wish.

I will now close this issue, it's sad to see this go, however, it is best that their wishes are respected."

**Comment by Dinoosawruss** [comment] 2020-12-11 01:37
Hi @Pixel1011,

I no longer have access to SmartRevise. If you want to do some tinkering to see if you can get it working feel free, I know @Ded-Ex contributed before if they'd like to take a look.

Let me know if you work anything out and feel free to post a pull request if you are able to make it work. I'll leave this issue open until I know it's fixed

I'll leave this issue open until it's working

**Comment by ghost** [comment] 2020-12-11 07:34
Hey,

@Pixel1011 I'll take a look at the issue tonight, just downloaded the code off the repo and can see what the problem is. 
I should be able to edit this and submit a pull request later with the fixed file so you can use that.

**Comment by Pixel1011** [comment] 2020-12-11 07:43
sounds good, also I haven't tested it with this myself since I was testing using my own code written in js but I'm going to assume the issue will be the same with this.

But essentially it doesn't let you go to any other part of the site except the login screen where if you try to login then it redirects you to the logout page and puts you back to the login page

**Comment by ghost** [comment] 2020-12-11 07:47
Yeah I noticed, rn I'm still unsure what that problem is but once I see a fix I'll be sure to let you know!
________________________________

**Comment by Dinoosawruss** [comment] 2020-12-11 16:21
@Ded-Ex perhaps they've added some form of time related checks? Could always try throwing some `time.sleep()`s in there 🤷‍♂️

**Comment by Dinoosawruss** [comment] 2020-12-11 22:30
Ok, so I signed up for a demo account and have taken a deeper look into this. 

I believe they may have added some system for detecting if the browser is a genuine browser or a web driver. 
If you open the web driver (both Firefox GeckDriver and ChromeWebDriver) and login manually, it still does not log you in.  

*To my knowledge* there is no way to run any selenium program without a web driver for it to run on (essentially it cannot run on the normal browsers we use; instead, it must run on a version built specifically for that). 

If this is the case, I don't see a way at this time to get anything to work - unless selenium or some other web tool is able to run on the main browser.

It would be a shame to see this no longer work as I feel a fair bit of attachment to this project as you can see I was able to get to 5000 questions attempted with it during lockdown as a joke. 

![image](https://user-images.githubusercontent.com/22278485/101960806-23030880-3c00-11eb-9a39-2053aafd8e1b.png)

I will leave this issue open as it is *technically* still an issue, maybe someone might stumble upon this repo and know a way to fix it. However, for now, I think this can be accepted as something that we cannot fix.

**Comment by ghost** [comment] 2020-12-11 23:06
Agreed, been looking at it for a while and have come to the same conclusion. Best idea I've got at the moment is to try get the user to somehow manually login then run the bot but still this would be an issue as the website seems pretty good at detecting driver-controlled browsers.

When I get more time I'll look into it again but it is a shame for it to go like this.

**Comment by Pixel1011** [comment] 2020-12-11 23:22
i mean after some quick googling i have come across this https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver

could help

**Comment by Dinoosawruss** [comment] 2020-12-11 23:32
@Pixel1011 I'll give that a try tomorrow and see how it goes 🤞

**Comment by Dinoosawruss** [comment] 2020-12-13 14:02
I have attempted the following:

**Comment by Dinoosawruss** [comment] 2020-12-13 14:03
**UPDATE**

I have attempted the following

![image](https://user-images.githubusercontent.com/22278485/102014041-ecd29f80-3d4b-11eb-84de-8ace807f79e7.png)

Unfortunately, it would seem that SmartRevise is using a different method to check if a driver-controlled browser is connected as this has not worked for me. 

EDIT: I am going to try and get it to edit the user agent when it runs

**Comment by Dinoosawruss** [comment] 2020-12-13 15:08
**UPDATE**

Changing the user agent also failed with the following code:

```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from fake_useragent import UserAgent
from time import sleep
from random import randint
from secrets import username, password
import csv

class ReviseBot:
    def __init__(self):
        options = Options()
        ua = UserAgent()
        userAgent = ua.random
        print(userAgent)
        options.add_argument(f'user-agent={userAgent}')
        driver = webdriver.Chrome(chrome_options=options)
        
        self.driver = webdriver.Chrome(options=options)

.
.
.
```
*Code source: https://stackoverflow.com/questions/49565042/way-to-change-google-chrome-user-agent-in-selenium*

**Comment by Dinoosawruss** [comment] 2020-12-13 15:33
**UPDATE**

I have asked on StackOverflow to see if we get a solution from there

![image](https://user-images.githubusercontent.com/22278485/102016350-653f5d80-3d58-11eb-9c87-4d12f49f86ae.png)

You can view the StackOverflow post [here](https://stackoverflow.com/questions/65277150/how-to-stop-websites-detecting-that-youre-using-selenium)

**Comment by Dinoosawruss** [comment] 2020-12-13 15:43
**UPDATE**

Found a [section of SmartRevise](https://smartrevise.online/robots.txt) that requests that people do not use automation on their site. I feel it is best to respect this wish.

I will now close this issue, it's sad to see this go, however, it is best that their wishes are respected.

Thanks, @Ded-Ex and @Pixel1011 for your help on this issue.

**Closed as completed by Dinoosawruss** 2020-12-13 15:43 UTC
Labels: bug, cantfix
